name: PSQLConn

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  psql-conn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Database URLs
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
        run: |
          echo "Fetching database URLs from Gist..."
          DATABASE_URLS=$(curl -s "${CONFIG_URL}?cache-bypass=$(date +%s)")
          echo "$DATABASE_URLS" > db_urls.txt

      - name: Run PSQL queries
        run: |
          i=1
          DATABASE_URLS=$(cat db_urls.txt)
          for db_url in $DATABASE_URLS; do
            if ! psql "$db_url" -q -t -c "SELECT 1;"; then
              echo "Failed to connect to database no-$i"
            else
              echo "Connection successful to database no-$i"
            fi
            i=$((i+1))
          done
